name: Monitoring Stability

# Triggers when a pull_request or a push action is configured on master branch
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  generate_json_repos:
    strategy:
      matrix:
        owner: ["Privado-Demo"]
        repo_name: ["privado-analytics", "privado-accounts-api", "shift-privacy-left-app"]

    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Folder to store reports
        run: mkdir ${GITHUB_WORKSPACE}/reports && echo ${GITHUB_WORKSPACE} && echo ${GITHUB_REPOSITORY_OWNER}


      - name: Download CPU and Memory usage capture tool
        run: mkdir ${GITHUB_WORKSPACE}/tools && curl https://raw.githubusercontent.com/karan-batavia/monitoring-stability/master/capture_usage.sh --output ${GITHUB_WORKSPACE}/tools/capture_usage.sh

      - name: Start monitoring cpu and memory usage
        run: bash ${GITHUB_WORKSPACE}/tools/capture_usage.sh &

      # Setup python 3.8 in the pipeline
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Setup privado environment in the pipeline
      - name: Setup Privado Env
        run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash

      - name: Download the comparison tool
        run: curl https://raw.githubusercontent.com/karan-batavia/monitoring-stability/master/compare.py --output ${GITHUB_WORKSPACE}/tools/compare.py


      - name: Clone repository
        uses: actions/checkout@v2
        with:
          owner: ${{matrix.owner}}
          repository: ${{matrix.owner}}/${{matrix.repo_name}}
          path: ./repos/${{matrix.repo_name}}

      - name: Scan ${{matrix.owner}}/${{matrix.repo_name}} (stable) using privado scan
        run: ~/.privado/bin/privado scan --skip-upload ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}}

      - name: Store ${{matrix.repo_name}}.json (stable)
        run: mkdir ${GITHUB_WORKSPACE}/stable_results && cat ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}}/.privado/privado.json > ${GITHUB_WORKSPACE}/stable_results/${{matrix.repo_name}}.json

      - name: Pass JSON (stable) to the next job
        uses: actions/upload-artifact@master
        with:
          name: ${{matrix.repo_name}} (stable)
          path: ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}}/.privado/privado.json

      - name: Scan ${{matrix.owner}}/${{matrix.repo_name}} (dev) using privado scan
        run: cd ~/.privado/bin && PRIVADO_DEV=1 ./privado scan --overwrite --skip-upload ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}}

      - name: Store ${{matrix.repo_name}}.json (dev)
        run: mkdir ${GITHUB_WORKSPACE}/dev_results && cat ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}}/.privado/privado.json > ${GITHUB_WORKSPACE}/dev_results/${{matrix.repo_name}}.json

      - name: Compare the two results
        run: cd ${GITHUB_WORKSPACE}/tools && python ./compare.py ${GITHUB_WORKSPACE}/stable_results/${{matrix.repo_name}}.json ${GITHUB_WORKSPACE}/dev_results/${{matrix.repo_name}}.json 

      - name: Pass JSON (stable) to the next job
        uses: actions/upload-artifact@master
        with:
          name: ${{matrix.repo_name}} (dev)
          path: ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}}/.privado/privado.json

        # For every repository, clone, scan and store the generated JSON
        # For karan-batavia/${{matrix.repo_name}}
      

      # Alovoa/alovoa takes too much time >45 mins
      # For Alovoa/alovoa
      # - name: Cloning Alovoa/alovoa
      #   uses: actions/checkout@v2
      #   with:
      #     owner: 'Alovoa'
      #     repository: 'Alovoa/alovoa'
      #     path: ./repos/alovoa

      # - name: Check contents of the folder
      #   run: cd ./repos && ls -lha

      # - name: Scan Alovoa/alovoa using privado scan
      #   run: cd ~/.privado/bin && ./privado scan --skip-upload ${GITHUB_WORKSPACE}/repos/alovoa

      # - name: Store JSON
      #   run: cd ${GITHUB_WORKSPACE} && cat ${GITHUB_WORKSPACE}/repos/alovoa/.privado/privado.json > ${GITHUB_WORKSPACE}/stable_results/alovoa.json

      # Info -> access all cloned repos at ${GITHUB_WORKSPACE}/repos
      # Info -> access all generated JSON (stable privado) files at ${GITHUB_WORKSPACE}/stable_results
      # Info -> access all generated JSON  (dev privado ) files at ${GITHUB_WORKSPACE}/dev_results
      # Info -> access all the csv reports at ${GITHUB_WORKSPACE}/tools
  check_files:
    needs: generate_json_repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: idk.json
          path: ${GITHUB_WORKSPACE}
      - run: ${GITHUB_WORKSPACE}/idk.txt
        