name: Monitoring Stability

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Privado Env
        run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash && exit

  scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Use privado environment
        run: privado scan /privado-analytics