name: Monitoring Stability

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Privado Env
        run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
      
      - name: Cloning the Repo 
        uses: actions/checkout@v2
        with:
          owner: 'karan-batavia'
          repository: 'karan-batavia/privado-analytics'
      
      - name: Check working directory path
        run: pwd

      - name: Check if repo is cloned
        run: cd ~/.privado/bin && ./privado scan ~/work/privado-analytics/privado-analytics
      
      - name: Check working directory path
        run: pwd
      
