name: Monitoring Stability

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Privado Env
        run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
        
      - name : Activate Bash
        shell : source ~/.bashrc 
        run: echo $PATH      
        
      - name : Activate ZSH
        shell : source ~/.zshrc 
        run: echo $PATH

      - name : Switch to another terminal
        shell : . ~/.profile 
        run: echo $PATH

      - name: Cloning the Repo 
        uses: actions/checkout@v2
        with:
          owner: 'karan-batavia'
          repository: 'karan-batavia/privado-analytics'

      - name: Scan the Project
        run: privado scan /privado-analytics && cd /privado-analytics && ls -la
