name: Monitoring Stability


# Triggers when a pull_request or a push action is configured on master branch
on:
  push:
    branches: ['master']      
  pull_request:
    branches: ['master']
  

jobs:
  generate_json_repos:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      # Setup privado environment in the pipeline
      - name: Setup Privado Env
        run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
      

      # For every repository, clone, scan and store the generated JSON
      # For karan-batavia/privado-analytics
      - name: Cloning karan-batavia/privado-analytics 
        uses: actions/checkout@v2
        with:
          owner: 'karan-batavia'
          repository: 'karan-batavia/privado-analytics'
          path: ./repos/privado-analytics

      - name: Check contents of the folder
        run: cd ./repos && ls -lha

      # cannot simulate restarting the terminal behavior in the pipeline, so navigated to the installation path to run the tool
      - name: Scan karan-batavia/privado-analytics (main) using privado scan
        run: cd ~/.privado/bin && ./privado scan --skip-upload ${{github.workspace}}/repos/privado-analytics
        
      - name: Scan karan-batavia/privado-analytics (dev) using privado scan
        run: cd ~/.privado/bin && PRIVADO_DEV=1 ./privado scan --skip-upload ${{github.workspace}}/repos/privado-analytics

      - name: Store privado-analytics.json (stable)
        run: cd ~/work && mkdir stable_results && cat ${{github.workspace}}/repos/privado-analytics/.privado/privado.json > ~/work/results/privado-analytics.json

      - name: Store privado-analytics.json (dev)
        run: cd ~/work && mkdir dev_results && cat ${{github.workspace}}/repos/privado-analytics/.privado/privado.json > ~/work/results/privado-analytics.json
      
      # For Privado-Demo/privado-accounts-api
      - name: Cloning Privado-Demo/privado-accounts-api 
        uses: actions/checkout@v2
        with:
          owner: 'Privado-Demo'
          repository: 'Privado-Demo/privado-accounts-api'
          path: ./repos/privado-accounts-api


      # Check if all the expected directories are present or not
      - name: Check contents of the folder
        run: cd ./repos && ls -lha

      - name: Scan Privado-Demo/privado-accounts-api using privado scan
        run: cd ~/.privado/bin && ./privado scan --skip-upload ${{github.workspace}}/repos/privado-accounts-api
      
      - name: Store privado-accounts-api.json
        run: cd ~/work && cat ${{github.workspace}}/repos/privado-accounts-api/.privado/privado.json > ~/work/results/privado-accounts-api.json

        
      
      # For Privado-Demo/shift-privacy-left-app
      - name: Cloning Privado-Demo/shift-privacy-left-app 
        uses: actions/checkout@v2
        with:
          owner: 'Privado-Demo'
          repository: 'Privado-Demo/shift-privacy-left-app'
          path: ./repos/shift-privacy-left-app

      - name: Check contents of the folder
        run: cd ./repos && ls -lha

      - name: Scan Privado-Demo/shift-privacy-left-app using privado scan
        run: cd ~/.privado/bin && ./privado scan --skip-upload ${{github.workspace}}/repos/shift-privacy-left-app
      
      - name: Store shift-privacy-left-app.json
        run: cd ~/work && cat ${{github.workspace}}/repos/shift-privacy-left-app/.privado/privado.json > ~/work/results/shift-privacy-left-app.json
        
        
      # Alovoa/alovoa takes too much time >45 mins
        # For Alovoa/alovoa
      # - name: Cloning Alovoa/alovoa 
      #   uses: actions/checkout@v2
      #   with:
      #     owner: 'Alovoa'
      #     repository: 'Alovoa/alovoa'
      #     path: ./repos/alovoa

      # - name: Check contents of the folder
      #   run: cd ./repos && ls -lha

      # - name: Scan Alovoa/alovoa using privado scan
      #   run: cd ~/.privado/bin && ./privado scan --skip-upload ${{github.workspace}}/repos/alovoa
      
      # - name: Store JSON
      #   run: cd ~/work && cat ${{github.workspace}}/repos/alovoa/.privado/privado.json > ~/work/results/alovoa.json

        # Check if all the generated JSON files are present
      - name: Log Contents of generated JSON folder
        run: cd ~/work/results && ls -lha


      # Info -> access all cloned repos at ${GITHUB_WORKSPACE}/repos
      # Info -> access all generated JSON files at ~/worl/results