name: Monitoring Stability

on:
  workflow_dispatch:
    inputs:
      
  push:
    branches: ['master']      
  pull_request:
    branches: ['master']
  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Privado Env
        run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
      
      - name: Cloning the Repo 
        uses: actions/checkout@v2
        with:
          owner: 'karan-batavia'
          repository: 'karan-batavia/privado-analytics'

      - name: Scan the repo using privado scan
        run: cd ~/.privado/bin && ./privado scan --skip-upload ~/work/privado-analytics/privado-analytics
      
      - name: Output json
        run: cat ~/work/privado-analytics/privado-analytics/.privado/privado.json
      
