name: Monitoring Stability

on:
  push:
    branches: ['master']      
  pull_request:
    branches: ['master']
  

jobs:
  process_repo_1:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Get github workspace path
        run : echo ${{github.workspace}}

      - name: Get github workspace path v2
        run : echo $GITHUB_WORKSPACE

      - name: Setup Privado Env
        run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
      
      # For karan-batavia/privado-analytics
      - name: Cloning karan-batavia/privado-analytics 
        uses: actions/checkout@v2
        with:
          owner: 'karan-batavia'
          repository: 'karan-batavia/privado-analytics'
          path: ./repos/privado-analytics

      - name: Check contents of the folder
        run: cd ./repos && ls -lha

      - name: Scan karan-batavia/privado-analytics using privado scan
        run: cd ~/.privado/bin && ./privado scan --skip-upload ${{github.workspace}}/repos/privado-analytics
      
      - name: Store JSON
        run: cd ~/work && mkdir results && cat ${{github.workspace}}/repos/privado-analytics/.privado/privado.json > ~/work/results/privado-analytics.json
      
      - name: Read JSON
        run: cd ~/work/results && cat ./privado-analytics.json
      
      # For Privado-Demo/privado-accounts-api
      - name: Cloning Privado-Demo/privado-accounts-api 
        uses: actions/checkout@v2
        with:
          owner: 'Privado-Demo'
          repository: 'Privado-Demo/privado-accounts-api'
          path: ./repos/privado-accounts-api


      - name: Check contents of the folder
        run: cd ./repos && ls -lha

      - name: Scan Privado-Demo/privado-accounts-api using privado scan
        run: cd ~/.privado/bin && ./privado scan --skip-upload ${{github.workspace}}/repos/privado-accounts-api
      
      - name: Store JSON
        run: cd ~/work && cat ${{github.workspace}}/repos/privado-accounts-api/.privado/privado.json > ~/work/results/privado-accounts-api.json

        # Read all the generated JSON
      - name: Read JSON
        run: cd ~/work/results && cat ./privado-analytics.json && cat ./privado-accounts-api.json
        
      
      # For Privado-Demo/shift-privacy-left-app
      - name: Cloning Privado-Demo/shift-privacy-left-app 
        uses: actions/checkout@v2
        with:
          owner: 'Privado-Demo'
          repository: 'Privado-Demo/shift-privacy-left-app'
          path: ./repos/shift-privacy-left-app

      - name: Check contents of the folder
        run: cd ./repos && ls -lha

      - name: Scan Privado-Demo/shift-privacy-left-app using privado scan
        run: cd ~/.privado/bin && ./privado scan --skip-upload ${{github.workspace}}/repos/shift-privacy-left-app
      
      - name: Store JSON
        run: cd ~/work && cat ${{github.workspace}}/repos/shift-privacy-left-app/.privado/privado.json > ~/work/results/shift-privacy-left-app.json
        
        
        # For Privado-Demo/shift-privacy-left-app
      - name: Cloning Alovoa/alovoa 
        uses: actions/checkout@v2
        with:
          owner: 'Alovoa'
          repository: 'Alovoa/alovoa'
          path: ./repos/alovoa

      - name: Check contents of the folder
        run: cd ./repos && ls -lha

      - name: Scan Alovoa/alovoa using privado scan
        run: cd ~/.privado/bin && ./privado scan --skip-upload ${{github.workspace}}/repos/alovoa
      
      - name: Store JSON
        run: cd ~/work && cat ${{github.workspace}}/repos/alovoa/.privado/privado.json > ~/work/results/alovoa.json

        # Read all the generated JSON
      - name: Read JSON
        run: cd ~/work/results && ls -lha


      # For Privado-Demo/shift-privacy-left-app